# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - export YB_REGISTRY_USER="testde"
  - export YB_REGISTRY=hub.yottab.io
  - export YB_REGISTRY_REPO="$YB_REGISTRY/$YB_REGISTRY_USER/bomb-server" 
  - docker login -u "$YB_REGISTRY_USER" -p "$YB_REGISTRY_PASSWORD" "$YB_REGISTRY"

build-master:
  stage: build
  script:
    - docker build -t "$YB_REGISTRY_REPO:latest" . -f Dockerfile
    - docker push "$YB_REGISTRY_REPO:latest"
    
  only:
    - master

build-tags:
  stage: build
  script:
    - docker build -t "$YB_REGISTRY_REPO:$CI_COMMIT_TAG" . -f debug.Dockerfile
    - docker push "$YB_REGISTRY_REPO:$CI_COMMIT_TAG"

  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^v.*$/
